### ISSUE TITLE
[FEATURE] Implement Todo List

### ISSUE THREAD

**Issue by L-U-Ready** [LearnMate-Dev/LearnMate_BE#12]
### ✨ 이슈 내용
> 세부 일정 추천 기능 구현

### 💡 작업 내용
- [x] Todo List 조회
~- [ ] Todo 작성~
- [x] Todo 상세 조회 ( + 가이드)
- [x] Todo 가이드 재생성
- [x] Todo 삭제
